export const buttons = [
  'bold',
  'strikethrough',
  'underline',
  'italic',
  '|',
  'align',
  '|',
  'ul',
  'ol',
  '|',
  'image',
  'link',
  '|',
  'fullsize',
  'selectall',
];
export const editorConfig = {
  readonly: false,
  toolbar: true,
  spellcheck: true,
  language: 'en',
  toolbarAdaptive: true,
  showCharsCounter: false,
  showWordsCounter: false,
  showXPathInStatusbar: false,
  askBeforePasteHTML: true,
  askBeforePasteFromWord: true,
  buttons,
  uploader: {
    insertImageAsBase64URI: true,
  },
  height: 500,
  allowResizeY: false,
};
