export const buttons = [
  'bold',
  'strikethrough',
  'underline',
  'italic',
  '|',
  'align',
  '|',
  'ul',
  'ol',
  '|',
  'link',
];
export const editorConfig = {
  placeholder: '',
  readonly: false,
  toolbar: true,
  spellcheck: true,
  language: 'en',
  toolbarAdaptive: false,
  showCharsCounter: false,
  showWordsCounter: false,
  showXPathInStatusbar: false,
  askBeforePasteHTML: true,
  askBeforePasteFromWord: true,
  buttons,
  uploader: {
    insertImageAsBase64URI: true,
  },
  height: 300,
  maxHeight: 500,
  allowResizeY: false,
};
